### ISSUE TITLE
Call to a member function each() on null

### ISSUE THREAD

**Issue by robin-dongbin** [sourcetoad/enhanced-resources#28] opened 2022-09-26 07:57 UTC
When use `PostResource::collection($this->whenLoaded('posts'))->format('api')` and it is not loaded will cause this error.

https://github.com/sourcetoad/enhanced-resources/blob/9e2d9b3a8beefe314e301e9dcb15085cb16986a0/src/ResourceCollection.php#L41

**Comment by iBotPeaches** [comment] 2022-09-26 12:18
@Jasonej - Do you mind triaging this?

**Comment by Jasonej** [comment] 2022-09-26 13:50
Hi @winter-ice,

It looks like what's happening is the `whenLoaded` is returning a `MissingValue` which is causing the collection to be null. Fixing line 41 just results in a very similar error (`Call to a member function map() on null`) being thrown from the underlying ResourceCollection code that's part of Laravel. Handling that error still creates unexpected behavior with the resulting value during the resource's `resolve()` call being an empty array rather than persisting the `MissingValue`.

I'll brainstorm a solution to this problem that will preserve the `MissingValue` behavior, but in the mean time there are a couple of options that can achieve the same behavior:

1. If you're okay with the empty array output you can provide an empty array as the default value for your `whenLoaded` call:
```php
PostResource::collection($this->whenLoaded('posts', null, []))->format('api');
```

2. If you want to preserve the `MissingValue` functionality, you can perform the loaded check outside of the collection:
```php
$this->resource->relationLoaded('posts')
    ? PostResource::collection($this->resource->posts)->format('api')
    : new MissingLoaded;
```

**Comment by robin-dongbin** [comment] 2022-09-27 01:24
Thanks for you reply.
I know there are some options can resolve this.

But this usage `PostResource::collection($this->whenLoaded('posts'))` is in the laravel docs.
I think this package should make sure that the laravel documented usages works.
Hope you can find a solution.

**Comment by Jasonej** [comment] 2024-03-08 18:57
Hi, I've recently been able to take a closer look at this and I find that the behavior is the same as with Laravel's base resources.

I created four resources to validate this (two enhanced, two base):

TestResource.php
```php
<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\MissingValue;
use Sourcetoad\EnhancedResources\Formatting\Attributes\Format;

class TestResource extends Resource
{
    #[Format]
    public function base(): array
    {
        return [
            'other' => OtherResource::collection(new MissingValue()),
        ];
    }
}
```

OtherResource.php
```php
<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Sourcetoad\EnhancedResources\Formatting\Attributes\Format;

class OtherResource extends Resource
{
    #[Format]
    public function base(): array
    {
        return [];
    }
}
```

TestBaseResource.php
```php
<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\MissingValue;

class TestBaseResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'other' => OtherBaseResource::collection(new MissingValue()),
        ];
    }
}

```

OtherBaseResource.php
```php
<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class OtherBaseResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [];
    }
}
```

I then ran the following in tinker, and both versions output the same response content.

```
> App\Http\Resources\TestResource::make(new stdClass)->response()->getContent();
= "{"data":[]}"

> App\Http\Resources\TestBaseResource::make(new stdClass)->response()->getContent();
= "{"data":[]}"
```

I also ran the collection missing value directly and got the same error in both versions

```
> App\Http\Resources\OtherResource::collection(new Illuminate\Http\Resources\MissingValue())->response();

   WARNING  Attempt to read property "map" on null in vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php on line 102.


   Error  Call to a member function toArray() on null.

> App\Http\Resources\OtherBaseResource::collection(new Illuminate\Http\Resources\MissingValue())->response();

   WARNING  Attempt to read property "map" on null in vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php on line 102.


   Error  Call to a member function toArray() on null.
```

The expected behavior of a collection with a missing value nested inside another resource is working correctly at this point, so I'm closing this issue.

**Closed as completed by Jasonej** 2024-03-08 18:57 UTC
